apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- service-active.yaml
- service-preview.yaml
- rollout.yaml

configMapGenerator:
- name: blue-config
  files:
  - blue-conf/index.html
- name: green-config
  files:
  - green-conf/index.html
