apiVersion: v1
kind: Service
metadata:
  labels:
    ms: super-ms
  name: super-ms-active
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    ms: super-ms
  type: ClusterIP
